### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by dalareo** [abernix/meteord#7]
Thanks @abernix for this project, is really great!! I wonder if there is any way of making image size smaller. My project is almost a one-page-app and its size is 1,35GB!!

**Comment by abernix** [comment]
Yeah, nothing about the final image size is efficient due to the caching layers involved.  If size is your concern, I recommend taking a look at the [forum thread](https://forums.meteor.com/t/docker-team-up-to-create-a-reference-docker-image-for-meteor/30829/46) about Docker images, namely the MiniMeteor image.

I'm happy to consider ways of decreasing this, but it will likely turn into another project entirely and break many aspects of this (which is a compatibility project to maintain Meteor 1.4 support with Mup).  There are better ways to deploy Meteor applications at this point without Mup and Meteord, even though those still work.

**Comment by dalareo** [comment]
Thanks!! Minimeteor is reaaaaally small

**Comment by houshuang** [comment]
@abernix Could you please elaborate on this:  

> There are better ways to deploy Meteor applications at this point without Mup and Meteord

What are better options for doing installs on servers we control (not Galaxy)? We're using 1.6 beta. 

Thanks!

**Comment by abernix** [comment]
I think that forum thread has some reasonable suggestions for other Docker images.  That's not to say that this image won't work just fine (it will!), but if you're trying to have a "microservice" with lots of running containers a 1GB image is too large (especially when it _could_ be a quarter or less of that size).

If you're running a single container, and don't mind the slower upload speed (which is less of a problem if you're deploying from CircleCI/Travis or something) it's probably fine to use this image.  Of course, above one container, things (balancing connections, etc.) becomes more important and there is no substitute for a proper host to alleviate the pain points of managing the hosting.

**Comment by houshuang** [comment]
Thanks a lot for your feedback. I was especially wondering if you thought Mup was superceded by something better, or we should just roll our own Docker images... Just beginning to figure out deployment of an app we've been working on for a year, first trial will be in a lecture hall where 350 students load the app simultaneously, so we are planning to do a lot of testing of different setups in the next month, finding the pain points with scaling etc. Thanks!!
